2017-11-09 11:03:43.764 [error] <0.616.0> /home/pampa/pampa_pro/src/pampa_pro_app.erl:9: Error: record amqp_params_direct undefined
/home/pampa/pampa_pro/src/pampa_pro_app.erl:9: Warning: variable 'Connection' is unused
2017-11-09 11:06:28.794 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}}) line 239
2017-11-09 11:06:28.794 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}}) line 239
2017-11-09 11:06:28.795 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}}) line 239 in context child_terminated
2017-11-09 11:06:28.795 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:06:28.795 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@127.0.0.1.2.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510196788794},{node,'pampa_pro@127.0.0.1'},{user_who_performed_action,none}]],[]},{...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:08:09.505 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}}) line 239
2017-11-09 11:08:09.505 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}}) line 239
2017-11-09 11:08:09.505 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}}) line 239 in context child_terminated
2017-11-09 11:08:09.506 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:08:09.506 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@127.0.0.1.1.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510196889505},{node,'pampa_pro@127.0.0.1'},{user_who_performed_action,none}]],[]},{...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:08:59.869 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:08:59.870 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:08:59.870 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239 in context child_terminated
2017-11-09 11:08:59.870 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:08:59.870 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@localhost.2.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510196939869},{node,pampa_pro@localhost},{user_who_performed_action,none}]],[]},{rpc,...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:11:25.878 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}}) line 239
2017-11-09 11:11:25.879 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}}) line 239
2017-11-09 11:11:25.879 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}}) line 239 in context child_terminated
2017-11-09 11:11:25.879 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:11:25.879 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@VM_0_14_centos.3.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510197085878},{node,pampa_pro@VM_0_14_centos},{user_who_performed_action,none}]],...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:13:25.721 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}}) line 239
2017-11-09 11:13:25.721 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}}) line 239
2017-11-09 11:13:25.721 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}}) line 239 in context child_terminated
2017-11-09 11:13:25.721 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:13:25.722 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@VM_0_14_centos.1.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510197205720},{node,pampa_pro@VM_0_14_centos},{user_who_performed_action,none}]],...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:16:16.750 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:16:16.750 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:16:16.751 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239 in context child_terminated
2017-11-09 11:16:16.751 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:16:16.751 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@localhost.2.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510197376749},{node,pampa_pro@localhost},{user_who_performed_action,none}]],[]},{rpc,...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:37:42.115 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:37:42.115 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:37:42.116 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239 in context child_terminated
2017-11-09 11:37:42.116 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:37:42.116 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@localhost.3.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510198662115},{node,pampa_pro@localhost},{user_who_performed_action,none}]],[]},{rpc,...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:38:59.503 [error] <0.669.0>@amqp_connection:start_direct CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: call to undefined function amqp_connection:start_direct() in application_master:init/4 line 134
2017-11-09 11:45:43.226 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:45:43.226 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:45:43.226 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239 in context child_terminated
2017-11-09 11:45:43.226 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:45:43.226 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@localhost.2.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510199143225},{node,pampa_pro@localhost},{user_who_performed_action,none}]],[]},{rpc,...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:54:17.973 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 11:54:17.973 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 11:54:17.974 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239 in context child_terminated
2017-11-09 11:54:17.974 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:54:17.974 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.94381411>],[{file,"gen.erl"},{line,253}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,210}]},{rpc,do_call,3,[{file,"rpc.erl"},{line,327}]},{amqp_direct_connection,connect,4,[{file,"src/amqp_direct_connection.erl"},{line,151}]},{amqp_gen_connection,handle_call,3,[{file,"src/amqp_gen_connection.erl"},{line,171}]},{gen_server,try_handle_call,...},...]},...}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 12:12:54.065 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:12:54.066 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:12:54.066 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239 in context child_terminated
2017-11-09 12:12:54.066 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 12:12:54.066 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.94381411>],[{file,"gen.erl"},{line,253}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,210}]},{rpc,do_call,3,[{file,"rpc.erl"},{line,327}]},{amqp_direct_connection,connect,4,[{file,"src/amqp_direct_connection.erl"},{line,151}]},{amqp_gen_connection,handle_call,3,[{file,"src/amqp_gen_connection.erl"},{line,171}]},{gen_server,try_handle_call,...},...]},...}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 12:16:03.279 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:16:03.280 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:16:03.280 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239 in context child_terminated
2017-11-09 12:16:03.280 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 12:16:03.280 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.94381411>],[{file,"gen.erl"},{line,253}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,210}]},{rpc,do_call,3,[{file,"rpc.erl"},{line,327}]},{amqp_direct_connection,connect,4,[{file,"src/amqp_direct_connection.erl"},{line,151}]},{amqp_gen_connection,handle_call,3,[{file,"src/amqp_gen_connection.erl"},{line,171}]},{gen_server,try_handle_call,...},...]},...}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 12:21:27.294 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:21:27.294 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:21:27.295 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239 in context child_terminated
2017-11-09 12:21:27.295 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 12:21:27.295 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.94381411>],[{file,"gen.erl"},{line,253}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,210}]},{rpc,do_call,3,[{file,"rpc.erl"},{line,327}]},{amqp_direct_connection,connect,4,[{file,"src/amqp_direct_connection.erl"},{line,151}]},{amqp_gen_connection,handle_call,3,[{file,"src/amqp_gen_connection.erl"},{line,171}]},{gen_server,try_handle_call,...},...]},...}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 12:25:08.680 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:25:08.680 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:25:08.681 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239 in context child_terminated
2017-11-09 12:25:08.681 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 12:25:08.681 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.94381411>],[{file,"gen.erl"},{line,253}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,210}]},{rpc,do_call,3,[{file,"rpc.erl"},{line,327}]},{amqp_direct_connection,connect,4,[{file,"src/amqp_direct_connection.erl"},{line,151}]},{amqp_gen_connection,handle_call,3,[{file,"src/amqp_gen_connection.erl"},{line,171}]},{gen_server,try_handle_call,...},...]},...}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 12:25:35.341 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 12:25:35.341 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 12:25:35.341 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239 in context child_terminated
2017-11-09 12:25:35.341 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 12:25:35.342 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@localhost.2.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510201535340},{node,pampa_pro@localhost},{user_who_performed_action,none}]],[]},{rpc,...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 12:26:45.862 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 12:26:45.862 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 12:26:45.863 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239 in context child_terminated
2017-11-09 12:26:45.863 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 12:26:45.863 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@localhost.3.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510201605862},{node,pampa_pro@localhost},{user_who_performed_action,none}]],[]},{rpc,...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 14:04:12.595 [error] <0.616.0> /home/pampa/pampa_pro/src/ws_handler.erl:1: Error: no module definition
2017-11-09 14:06:03.845 [error] <0.616.0> /home/pampa/pampa_pro/src/msger.erl:1: Error: no module definition
2017-11-09 14:23:43.955 [error] <0.616.0> /home/pampa/pampa_pro/src/ws_handler.erl:16: Warning: variable 'WsId' is unused
/home/pampa/pampa_pro/src/ws_handler.erl:19: Error: record ws_state undefined
/home/pampa/pampa_pro/src/ws_handler.erl:40: Warning: variable 'MsgerPid' is unused
/home/pampa/pampa_pro/src/ws_handler.erl:42: Error: record ws_state undefined
/home/pampa/pampa_pro/src/ws_handler.erl:44: Error: record ws_state undefined
/home/pampa/pampa_pro/src/ws_handler.erl:59: Error: record ws_state undefined
/home/pampa/pampa_pro/src/ws_handler.erl:65: Error: record ws_state undefined
/home/pampa/pampa_pro/src/ws_handler.erl:90: Error: record ws_state undefined
/home/pampa/pampa_pro/src/ws_handler.erl:91: Error: record ws_state undefined
2017-11-09 14:25:56.451 [error] <0.616.0> /home/pampa/pampa_pro/src/msger.erl:9: Warning: variable 'WsPid' is unused
/home/pampa/pampa_pro/src/msger.erl:26: Warning: variable 'Tag' is unused
/home/pampa/pampa_pro/src/msger.erl:36: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:58: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:63: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:68: Error: record msger_state undefined
2017-11-09 14:26:05.573 [error] <0.616.0> /home/pampa/pampa_pro/src/msger.erl:9: Warning: variable 'WsPid' is unused
/home/pampa/pampa_pro/src/msger.erl:26: Warning: variable 'Tag' is unused
/home/pampa/pampa_pro/src/msger.erl:36: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:58: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:63: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:68: Error: record msger_state undefined
2017-11-09 14:26:19.757 [error] <0.616.0> /home/pampa/pampa_pro/src/msger.erl:9: Warning: variable 'WsPid' is unused
/home/pampa/pampa_pro/src/msger.erl:26: Warning: variable 'Tag' is unused
/home/pampa/pampa_pro/src/msger.erl:36: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:58: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:63: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:68: Error: record msger_state undefined
2017-11-09 15:17:59.379 [error] <0.3378.0>@cowboy_req:reply:706 CRASH REPORT Process <0.3378.0> with 0 neighbours crashed with reason: bad argument in call to erlang:iolist_size([{<<"egheoin">>,true}]) in cowboy_req:reply/4 line 706
2017-11-09 15:17:59.380 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.3377.0>,1,<0.3378.0>,badarg,[{erlang,iolist_size,[[{<<"egheoin">>,true}]],[]},{cowboy_req,reply,4,[{file,"src/cowboy_req.erl"},{line,706}]},{http_handler,handle,3,[{file,"src/http_handler.erl"},{line,29}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,3,[{file,"src/cowboy_stream_h.erl"},{line,184}]},{proc_lib,init_p_do_apply,...}]]},...}}
2017-11-09 15:18:02.263 [error] <0.3389.0>@cowboy_req:reply:706 CRASH REPORT Process <0.3389.0> with 0 neighbours crashed with reason: bad argument in call to erlang:iolist_size([{<<"egheoin">>,true}]) in cowboy_req:reply/4 line 706
2017-11-09 15:18:02.264 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.3388.0>,1,<0.3389.0>,badarg,[{erlang,iolist_size,[[{<<"egheoin">>,true}]],[]},{cowboy_req,reply,4,[{file,"src/cowboy_req.erl"},{line,706}]},{http_handler,handle,3,[{file,"src/http_handler.erl"},{line,29}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,3,[{file,"src/cowboy_stream_h.erl"},{line,184}]},{proc_lib,init_p_do_apply,...}]]},...}}
2017-11-09 15:19:32.754 [error] <0.3600.0>@cowboy_req:reply:706 CRASH REPORT Process <0.3600.0> with 0 neighbours crashed with reason: bad argument in call to erlang:iolist_size([{<<"foo">>,<<"bar">>}]) in cowboy_req:reply/4 line 706
2017-11-09 15:19:32.756 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.3599.0>,1,<0.3600.0>,badarg,[{erlang,iolist_size,[[{<<"foo">>,<<"bar">>}]],[]},{cowboy_req,reply,4,[{file,"src/cowboy_req.erl"},{line,706}]},{http_handler,handle,3,[{file,"src/http_handler.erl"},{line,29}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,3,[{file,"src/cowboy_stream_h.erl"},{line,184}]},{proc_lib,init_p_do_apply,...}]]},...}}
2017-11-09 15:21:45.036 [error] <0.3912.0>@http_handler:handle:38 CRASH REPORT Process <0.3912.0> with 0 neighbours crashed with reason: no match of right hand value #{<<"echo1">> => <<"bar">>} in http_handler:handle/3 line 38
2017-11-09 15:21:45.037 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.3911.0>,1,<0.3912.0>,{badmatch,#{<<"echo1">> => <<"bar">>}},[{http_handler,handle,3,[{file,"/home/pampa/pampa_pro/src/http_handler.erl"},{line,38}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,3,[{file,"src/cowboy_stream_h.erl"},{line,184}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]]},[{error_logger_lager_h,...},...]}}
2017-11-09 15:22:18.282 [error] <0.619.0> /home/pampa/pampa_pro/src/http_handler.erl:36: Warning: variable 'Echo' is unused
/home/pampa/pampa_pro/src/http_handler.erl:37: Error: variable 'Other' is unbound
2017-11-09 15:22:22.334 [error] <0.619.0> /home/pampa/pampa_pro/src/http_handler.erl:36: Warning: variable 'Echo' is unused
/home/pampa/pampa_pro/src/http_handler.erl:37: Error: variable '_Other' is unbound
2017-11-09 15:22:33.456 [error] <0.619.0> /home/pampa/pampa_pro/src/http_handler.erl:37: Error: variable '_Other' is unbound
2017-11-09 15:22:41.472 [error] <0.4053.0>@http_handler:handle:38 CRASH REPORT Process <0.4053.0> with 0 neighbours crashed with reason: no match of right hand value #{<<"echo1">> => <<"bar">>} in http_handler:handle/3 line 38
2017-11-09 15:22:41.473 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.4052.0>,1,<0.4053.0>,{badmatch,#{<<"echo1">> => <<"bar">>}},[{http_handler,handle,3,[{file,"/home/pampa/pampa_pro/src/http_handler.erl"},{line,38}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,3,[{file,"src/cowboy_stream_h.erl"},{line,184}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]]},[{error_logger_lager_h,...},...]}}
2017-11-09 15:23:08.810 [error] <0.619.0> /home/pampa/pampa_pro/src/http_handler.erl:37: Error: variable '_Other' is unbound
2017-11-09 15:23:16.220 [error] <0.4139.0>@http_handler:handle:38 CRASH REPORT Process <0.4139.0> with 0 neighbours crashed with reason: no match of right hand value #{<<"echo1">> => <<"bar">>} in http_handler:handle/3 line 38
2017-11-09 15:23:16.221 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.4138.0>,1,<0.4139.0>,{badmatch,#{<<"echo1">> => <<"bar">>}},[{http_handler,handle,3,[{file,"/home/pampa/pampa_pro/src/http_handler.erl"},{line,38}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,3,[{file,"src/cowboy_stream_h.erl"},{line,184}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]]},[{error_logger_lager_h,...},...]}}
2017-11-09 15:23:18.109 [error] <0.4148.0>@http_handler:handle:38 CRASH REPORT Process <0.4148.0> with 0 neighbours crashed with reason: no match of right hand value #{<<"echo1">> => <<"bar">>} in http_handler:handle/3 line 38
2017-11-09 15:23:18.110 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.4147.0>,1,<0.4148.0>,{badmatch,#{<<"echo1">> => <<"bar">>}},[{http_handler,handle,3,[{file,"/home/pampa/pampa_pro/src/http_handler.erl"},{line,38}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,3,[{file,"src/cowboy_stream_h.erl"},{line,184}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]]},[{error_logger_lager_h,...},...]}}
2017-11-09 15:23:35.094 [error] <0.619.0> /home/pampa/pampa_pro/src/http_handler.erl:1: Error: no module definition
2017-11-09 15:23:53.277 [error] <0.619.0> /home/pampa/pampa_pro/src/http_handler.erl:45: Error: variable 'OtherValue' is unbound
2017-11-09 15:24:17.226 [error] <0.4301.0>@cowboy_req:do_reply:712 CRASH REPORT Process <0.4301.0> with 0 neighbours crashed with reason: no function clause matching cowboy_req:do_reply(200, #{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>}, <<>>, <<"bar">>) line 712
2017-11-09 15:24:17.228 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.4300.0>,1,<0.4301.0>,function_clause,[{cowboy_req,do_reply,[200,#{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>},<<>>,<<"bar">>],[{file,"src/cowboy_req.erl"},{line,712}]},{http_handler,handle,3,[{file,"/home/pampa/pampa_pro/src/http_handler.erl"},{line,42}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,...},...]]},...}}
2017-11-09 15:24:19.297 [error] <0.4307.0>@cowboy_req:do_reply:712 CRASH REPORT Process <0.4307.0> with 0 neighbours crashed with reason: no function clause matching cowboy_req:do_reply(200, #{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>}, <<>>, <<"bar\\">>) line 712
2017-11-09 15:24:19.299 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.4306.0>,1,<0.4307.0>,function_clause,[{cowboy_req,do_reply,[200,#{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>},<<>>,<<"bar\\">>],[{file,"src/cowboy_req.erl"},{line,712}]},{http_handler,handle,3,[{file,"/home/pampa/pampa_pro/src/http_handler.erl"},{line,42}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,...},...]]},...}}
2017-11-09 15:24:20.706 [error] <0.4314.0>@cowboy_req:do_reply:712 CRASH REPORT Process <0.4314.0> with 0 neighbours crashed with reason: no function clause matching cowboy_req:do_reply(200, #{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>}, <<>>, <<"bar">>) line 712
2017-11-09 15:24:20.707 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.4313.0>,1,<0.4314.0>,function_clause,[{cowboy_req,do_reply,[200,#{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>},<<>>,<<"bar">>],[{file,"src/cowboy_req.erl"},{line,712}]},{http_handler,handle,3,[{file,"/home/pampa/pampa_pro/src/http_handler.erl"},{line,42}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,...},...]]},...}}
2017-11-09 15:24:41.818 [error] <0.619.0> /home/pampa/pampa_pro/src/http_handler.erl:24: Error: function handle/3 undefined
/home/pampa/pampa_pro/src/http_handler.erl:39: Error: syntax error before: '}'
2017-11-09 15:24:43.422 [error] <0.4372.0>@cowboy_req:do_reply:712 CRASH REPORT Process <0.4372.0> with 0 neighbours crashed with reason: no function clause matching cowboy_req:do_reply(200, #{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>}, <<>>, <<"bar">>) line 712
2017-11-09 15:24:43.423 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.4371.0>,1,<0.4372.0>,function_clause,[{cowboy_req,do_reply,[200,#{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>},<<>>,<<"bar">>],[{file,"src/cowboy_req.erl"},{line,712}]},{http_handler,handle,3,[{file,"/home/pampa/pampa_pro/src/http_handler.erl"},{line,42}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,...},...]]},...}}
2017-11-09 15:24:45.381 [error] <0.4379.0>@cowboy_req:do_reply:712 CRASH REPORT Process <0.4379.0> with 0 neighbours crashed with reason: no function clause matching cowboy_req:do_reply(200, #{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>}, <<>>, <<"bar">>) line 712
2017-11-09 15:24:45.383 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.4378.0>,1,<0.4379.0>,function_clause,[{cowboy_req,do_reply,[200,#{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>},<<>>,<<"bar">>],[{file,"src/cowboy_req.erl"},{line,712}]},{http_handler,handle,3,[{file,"/home/pampa/pampa_pro/src/http_handler.erl"},{line,42}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,...},...]]},...}}
2017-11-09 15:24:46.206 [error] <0.4385.0>@cowboy_req:do_reply:712 CRASH REPORT Process <0.4385.0> with 0 neighbours crashed with reason: no function clause matching cowboy_req:do_reply(200, #{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>}, <<>>, <<"bar">>) line 712
2017-11-09 15:24:46.207 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.4384.0>,1,<0.4385.0>,function_clause,[{cowboy_req,do_reply,[200,#{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>},<<>>,<<"bar">>],[{file,"src/cowboy_req.erl"},{line,712}]},{http_handler,handle,3,[{file,"/home/pampa/pampa_pro/src/http_handler.erl"},{line,42}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,...},...]]},...}}
2017-11-09 15:26:24.903 [error] <0.619.0> /home/pampa/pampa_pro/src/http_handler.erl:52: Error: function handle/3 already defined
2017-11-09 15:28:20.140 [error] <0.619.0> /home/pampa/pampa_pro/src/tcp_handler.erl:1: Error: no module definition
2017-11-09 16:15:50.354 [error] <0.620.0> /home/pampa/pampa_pro/src/tcp_handler.erl:17: Error: function loop/2 undefined
/home/pampa/pampa_pro/src/tcp_handler.erl:20: Error: undefined macro 'TCP_TIMEOUT_MS'
