2017-11-09 11:03:43.764 [error] <0.616.0> /home/pampa/pampa_pro/src/pampa_pro_app.erl:9: Error: record amqp_params_direct undefined
/home/pampa/pampa_pro/src/pampa_pro_app.erl:9: Warning: variable 'Connection' is unused
2017-11-09 11:06:28.794 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}}) line 239
2017-11-09 11:06:28.794 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}}) line 239
2017-11-09 11:06:28.795 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}}) line 239 in context child_terminated
2017-11-09 11:06:28.795 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:06:28.795 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@127.0.0.1.2.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510196788794},{node,'pampa_pro@127.0.0.1'},{user_who_performed_action,none}]],[]},{...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:08:09.505 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}}) line 239
2017-11-09 11:08:09.505 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}}) line 239
2017-11-09 11:08:09.505 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}}) line 239 in context child_terminated
2017-11-09 11:08:09.506 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,'pampa_pro@127.0.0.1',none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:08:09.506 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@127.0.0.1.1.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510196889505},{node,'pampa_pro@127.0.0.1'},{user_who_performed_action,none}]],[]},{...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:08:59.869 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:08:59.870 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:08:59.870 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239 in context child_terminated
2017-11-09 11:08:59.870 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:08:59.870 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@localhost.2.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510196939869},{node,pampa_pro@localhost},{user_who_performed_action,none}]],[]},{rpc,...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:11:25.878 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}}) line 239
2017-11-09 11:11:25.879 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}}) line 239
2017-11-09 11:11:25.879 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}}) line 239 in context child_terminated
2017-11-09 11:11:25.879 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:11:25.879 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@VM_0_14_centos.3.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510197085878},{node,pampa_pro@VM_0_14_centos},{user_who_performed_action,none}]],...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:13:25.721 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}}) line 239
2017-11-09 11:13:25.721 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}}) line 239
2017-11-09 11:13:25.721 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}}) line 239 in context child_terminated
2017-11-09 11:13:25.721 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@VM_0_14_centos,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:13:25.722 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@VM_0_14_centos.1.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510197205720},{node,pampa_pro@VM_0_14_centos},{user_who_performed_action,none}]],...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:16:16.750 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:16:16.750 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:16:16.751 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239 in context child_terminated
2017-11-09 11:16:16.751 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:16:16.751 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@localhost.2.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510197376749},{node,pampa_pro@localhost},{user_who_performed_action,none}]],[]},{rpc,...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:37:42.115 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:37:42.115 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:37:42.116 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239 in context child_terminated
2017-11-09 11:37:42.116 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:37:42.116 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@localhost.3.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510198662115},{node,pampa_pro@localhost},{user_who_performed_action,none}]],[]},{rpc,...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:38:59.503 [error] <0.669.0>@amqp_connection:start_direct CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: call to undefined function amqp_connection:start_direct() in application_master:init/4 line 134
2017-11-09 11:45:43.226 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:45:43.226 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 11:45:43.226 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239 in context child_terminated
2017-11-09 11:45:43.226 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:45:43.226 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@localhost.2.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510199143225},{node,pampa_pro@localhost},{user_who_performed_action,none}]],[]},{rpc,...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 11:54:17.973 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 11:54:17.973 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 11:54:17.974 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239 in context child_terminated
2017-11-09 11:54:17.974 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 11:54:17.974 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.94381411>],[{file,"gen.erl"},{line,253}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,210}]},{rpc,do_call,3,[{file,"rpc.erl"},{line,327}]},{amqp_direct_connection,connect,4,[{file,"src/amqp_direct_connection.erl"},{line,151}]},{amqp_gen_connection,handle_call,3,[{file,"src/amqp_gen_connection.erl"},{line,171}]},{gen_server,try_handle_call,...},...]},...}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 12:12:54.065 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:12:54.066 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:12:54.066 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239 in context child_terminated
2017-11-09 12:12:54.066 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 12:12:54.066 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.94381411>],[{file,"gen.erl"},{line,253}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,210}]},{rpc,do_call,3,[{file,"rpc.erl"},{line,327}]},{amqp_direct_connection,connect,4,[{file,"src/amqp_direct_connection.erl"},{line,151}]},{amqp_gen_connection,handle_call,3,[{file,"src/amqp_gen_connection.erl"},{line,171}]},{gen_server,try_handle_call,...},...]},...}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 12:16:03.279 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:16:03.280 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:16:03.280 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239 in context child_terminated
2017-11-09 12:16:03.280 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 12:16:03.280 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.94381411>],[{file,"gen.erl"},{line,253}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,210}]},{rpc,do_call,3,[{file,"rpc.erl"},{line,327}]},{amqp_direct_connection,connect,4,[{file,"src/amqp_direct_connection.erl"},{line,151}]},{amqp_gen_connection,handle_call,3,[{file,"src/amqp_gen_connection.erl"},{line,171}]},{gen_server,try_handle_call,...},...]},...}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 12:21:27.294 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:21:27.294 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:21:27.295 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239 in context child_terminated
2017-11-09 12:21:27.295 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 12:21:27.295 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.94381411>],[{file,"gen.erl"},{line,253}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,210}]},{rpc,do_call,3,[{file,"rpc.erl"},{line,327}]},{amqp_direct_connection,connect,4,[{file,"src/amqp_direct_connection.erl"},{line,151}]},{amqp_gen_connection,handle_call,3,[{file,"src/amqp_gen_connection.erl"},{line,171}]},{gen_server,try_handle_call,...},...]},...}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 12:25:08.680 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:25:08.680 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239
2017-11-09 12:25:08.681 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.9..>],...},...]},...}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,"/","localhost",none,[]}}) line 239 in context child_terminated
2017-11-09 12:25:08.681 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,"/","localhost",none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 12:25:08.681 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{{function_clause,[{gen,do_for_proc,[{rex,"localhost"},#Fun<gen.0.94381411>],[{file,"gen.erl"},{line,253}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,210}]},{rpc,do_call,3,[{file,"rpc.erl"},{line,327}]},{amqp_direct_connection,connect,4,[{file,"src/amqp_direct_connection.erl"},{line,151}]},{amqp_gen_connection,handle_call,3,[{file,"src/amqp_gen_connection.erl"},{line,171}]},{gen_server,try_handle_call,...},...]},...}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 12:25:35.341 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 12:25:35.341 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 12:25:35.341 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239 in context child_terminated
2017-11-09 12:25:35.341 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 12:25:35.342 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@localhost.2.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510201535340},{node,pampa_pro@localhost},{user_who_performed_action,none}]],[]},{rpc,...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 12:26:45.862 [error] <0.673.0>@amqp_gen_connection:terminate:239 gen_server <0.673.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 12:26:45.862 [error] <0.673.0>@amqp_gen_connection:terminate:239 CRASH REPORT Process <0.673.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239
2017-11-09 12:26:45.863 [error] <0.671.0>@amqp_gen_connection:terminate:239 Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason no function clause matching amqp_gen_connection:terminate({{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,...],...},...]}}}},...}, {<0.672.0>,{amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}}) line 239 in context child_terminated
2017-11-09 12:26:45.863 [error] <0.671.0> Supervisor {<0.671.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.672.0>, {amqp_params_direct,none,none,<<"/">>,pampa_pro@localhost,none,[]}) at <0.673.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 12:26:45.863 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{{case_clause,{badrpc,{'EXIT',{undef,[{rabbit_direct,connect,[{none,none},<<"/">>,rabbit_framing_amqp_0_9_1,<0.673.0>,[{pid,<0.673.0>},{protocol,{'Direct',{0,9,1}}},{host,unknown},{port,unknown},{name,<<"<pampa_pro@localhost.3.673.0>">>},{peer_host,unknown},{peer_port,unknown},{user,none},{vhost,<<"/">>},{client_properties,[]},{type,direct},{connected_at,1510201605862},{node,pampa_pro@localhost},{user_who_performed_action,none}]],[]},{rpc,...},...]}}}},...},...],...},...]},...} in application_master:init/4 line 134
2017-11-09 14:04:12.595 [error] <0.616.0> /home/pampa/pampa_pro/src/ws_handler.erl:1: Error: no module definition
2017-11-09 14:06:03.845 [error] <0.616.0> /home/pampa/pampa_pro/src/msger.erl:1: Error: no module definition
2017-11-09 14:23:43.955 [error] <0.616.0> /home/pampa/pampa_pro/src/ws_handler.erl:16: Warning: variable 'WsId' is unused
/home/pampa/pampa_pro/src/ws_handler.erl:19: Error: record ws_state undefined
/home/pampa/pampa_pro/src/ws_handler.erl:40: Warning: variable 'MsgerPid' is unused
/home/pampa/pampa_pro/src/ws_handler.erl:42: Error: record ws_state undefined
/home/pampa/pampa_pro/src/ws_handler.erl:44: Error: record ws_state undefined
/home/pampa/pampa_pro/src/ws_handler.erl:59: Error: record ws_state undefined
/home/pampa/pampa_pro/src/ws_handler.erl:65: Error: record ws_state undefined
/home/pampa/pampa_pro/src/ws_handler.erl:90: Error: record ws_state undefined
/home/pampa/pampa_pro/src/ws_handler.erl:91: Error: record ws_state undefined
2017-11-09 14:25:56.451 [error] <0.616.0> /home/pampa/pampa_pro/src/msger.erl:9: Warning: variable 'WsPid' is unused
/home/pampa/pampa_pro/src/msger.erl:26: Warning: variable 'Tag' is unused
/home/pampa/pampa_pro/src/msger.erl:36: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:58: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:63: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:68: Error: record msger_state undefined
2017-11-09 14:26:05.573 [error] <0.616.0> /home/pampa/pampa_pro/src/msger.erl:9: Warning: variable 'WsPid' is unused
/home/pampa/pampa_pro/src/msger.erl:26: Warning: variable 'Tag' is unused
/home/pampa/pampa_pro/src/msger.erl:36: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:58: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:63: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:68: Error: record msger_state undefined
2017-11-09 14:26:19.757 [error] <0.616.0> /home/pampa/pampa_pro/src/msger.erl:9: Warning: variable 'WsPid' is unused
/home/pampa/pampa_pro/src/msger.erl:26: Warning: variable 'Tag' is unused
/home/pampa/pampa_pro/src/msger.erl:36: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:58: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:63: Error: record msger_state undefined
/home/pampa/pampa_pro/src/msger.erl:68: Error: record msger_state undefined
2017-11-09 15:17:59.379 [error] <0.3378.0>@cowboy_req:reply:706 CRASH REPORT Process <0.3378.0> with 0 neighbours crashed with reason: bad argument in call to erlang:iolist_size([{<<"egheoin">>,true}]) in cowboy_req:reply/4 line 706
2017-11-09 15:17:59.380 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.3377.0>,1,<0.3378.0>,badarg,[{erlang,iolist_size,[[{<<"egheoin">>,true}]],[]},{cowboy_req,reply,4,[{file,"src/cowboy_req.erl"},{line,706}]},{http_handler,handle,3,[{file,"src/http_handler.erl"},{line,29}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,3,[{file,"src/cowboy_stream_h.erl"},{line,184}]},{proc_lib,init_p_do_apply,...}]]},...}}
2017-11-09 15:18:02.263 [error] <0.3389.0>@cowboy_req:reply:706 CRASH REPORT Process <0.3389.0> with 0 neighbours crashed with reason: bad argument in call to erlang:iolist_size([{<<"egheoin">>,true}]) in cowboy_req:reply/4 line 706
2017-11-09 15:18:02.264 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.3388.0>,1,<0.3389.0>,badarg,[{erlang,iolist_size,[[{<<"egheoin">>,true}]],[]},{cowboy_req,reply,4,[{file,"src/cowboy_req.erl"},{line,706}]},{http_handler,handle,3,[{file,"src/http_handler.erl"},{line,29}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,3,[{file,"src/cowboy_stream_h.erl"},{line,184}]},{proc_lib,init_p_do_apply,...}]]},...}}
2017-11-09 15:19:32.754 [error] <0.3600.0>@cowboy_req:reply:706 CRASH REPORT Process <0.3600.0> with 0 neighbours crashed with reason: bad argument in call to erlang:iolist_size([{<<"foo">>,<<"bar">>}]) in cowboy_req:reply/4 line 706
2017-11-09 15:19:32.756 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.3599.0>,1,<0.3600.0>,badarg,[{erlang,iolist_size,[[{<<"foo">>,<<"bar">>}]],[]},{cowboy_req,reply,4,[{file,"src/cowboy_req.erl"},{line,706}]},{http_handler,handle,3,[{file,"src/http_handler.erl"},{line,29}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,3,[{file,"src/cowboy_stream_h.erl"},{line,184}]},{proc_lib,init_p_do_apply,...}]]},...}}
2017-11-09 15:21:45.036 [error] <0.3912.0>@http_handler:handle:38 CRASH REPORT Process <0.3912.0> with 0 neighbours crashed with reason: no match of right hand value #{<<"echo1">> => <<"bar">>} in http_handler:handle/3 line 38
2017-11-09 15:21:45.037 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.3911.0>,1,<0.3912.0>,{badmatch,#{<<"echo1">> => <<"bar">>}},[{http_handler,handle,3,[{file,"/home/pampa/pampa_pro/src/http_handler.erl"},{line,38}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,3,[{file,"src/cowboy_stream_h.erl"},{line,184}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]]},[{error_logger_lager_h,...},...]}}
2017-11-09 15:22:18.282 [error] <0.619.0> /home/pampa/pampa_pro/src/http_handler.erl:36: Warning: variable 'Echo' is unused
/home/pampa/pampa_pro/src/http_handler.erl:37: Error: variable 'Other' is unbound
2017-11-09 15:22:22.334 [error] <0.619.0> /home/pampa/pampa_pro/src/http_handler.erl:36: Warning: variable 'Echo' is unused
/home/pampa/pampa_pro/src/http_handler.erl:37: Error: variable '_Other' is unbound
2017-11-09 15:22:33.456 [error] <0.619.0> /home/pampa/pampa_pro/src/http_handler.erl:37: Error: variable '_Other' is unbound
2017-11-09 15:22:41.472 [error] <0.4053.0>@http_handler:handle:38 CRASH REPORT Process <0.4053.0> with 0 neighbours crashed with reason: no match of right hand value #{<<"echo1">> => <<"bar">>} in http_handler:handle/3 line 38
2017-11-09 15:22:41.473 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.4052.0>,1,<0.4053.0>,{badmatch,#{<<"echo1">> => <<"bar">>}},[{http_handler,handle,3,[{file,"/home/pampa/pampa_pro/src/http_handler.erl"},{line,38}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,3,[{file,"src/cowboy_stream_h.erl"},{line,184}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]]},[{error_logger_lager_h,...},...]}}
2017-11-09 15:23:08.810 [error] <0.619.0> /home/pampa/pampa_pro/src/http_handler.erl:37: Error: variable '_Other' is unbound
2017-11-09 15:23:16.220 [error] <0.4139.0>@http_handler:handle:38 CRASH REPORT Process <0.4139.0> with 0 neighbours crashed with reason: no match of right hand value #{<<"echo1">> => <<"bar">>} in http_handler:handle/3 line 38
2017-11-09 15:23:16.221 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.4138.0>,1,<0.4139.0>,{badmatch,#{<<"echo1">> => <<"bar">>}},[{http_handler,handle,3,[{file,"/home/pampa/pampa_pro/src/http_handler.erl"},{line,38}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,3,[{file,"src/cowboy_stream_h.erl"},{line,184}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]]},[{error_logger_lager_h,...},...]}}
2017-11-09 15:23:18.109 [error] <0.4148.0>@http_handler:handle:38 CRASH REPORT Process <0.4148.0> with 0 neighbours crashed with reason: no match of right hand value #{<<"echo1">> => <<"bar">>} in http_handler:handle/3 line 38
2017-11-09 15:23:18.110 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.4147.0>,1,<0.4148.0>,{badmatch,#{<<"echo1">> => <<"bar">>}},[{http_handler,handle,3,[{file,"/home/pampa/pampa_pro/src/http_handler.erl"},{line,38}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,3,[{file,"src/cowboy_stream_h.erl"},{line,184}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]]},[{error_logger_lager_h,...},...]}}
2017-11-09 15:23:35.094 [error] <0.619.0> /home/pampa/pampa_pro/src/http_handler.erl:1: Error: no module definition
2017-11-09 15:23:53.277 [error] <0.619.0> /home/pampa/pampa_pro/src/http_handler.erl:45: Error: variable 'OtherValue' is unbound
2017-11-09 15:24:17.226 [error] <0.4301.0>@cowboy_req:do_reply:712 CRASH REPORT Process <0.4301.0> with 0 neighbours crashed with reason: no function clause matching cowboy_req:do_reply(200, #{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>}, <<>>, <<"bar">>) line 712
2017-11-09 15:24:17.228 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.4300.0>,1,<0.4301.0>,function_clause,[{cowboy_req,do_reply,[200,#{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>},<<>>,<<"bar">>],[{file,"src/cowboy_req.erl"},{line,712}]},{http_handler,handle,3,[{file,"/home/pampa/pampa_pro/src/http_handler.erl"},{line,42}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,...},...]]},...}}
2017-11-09 15:24:19.297 [error] <0.4307.0>@cowboy_req:do_reply:712 CRASH REPORT Process <0.4307.0> with 0 neighbours crashed with reason: no function clause matching cowboy_req:do_reply(200, #{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>}, <<>>, <<"bar\\">>) line 712
2017-11-09 15:24:19.299 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.4306.0>,1,<0.4307.0>,function_clause,[{cowboy_req,do_reply,[200,#{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>},<<>>,<<"bar\\">>],[{file,"src/cowboy_req.erl"},{line,712}]},{http_handler,handle,3,[{file,"/home/pampa/pampa_pro/src/http_handler.erl"},{line,42}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,...},...]]},...}}
2017-11-09 15:24:20.706 [error] <0.4314.0>@cowboy_req:do_reply:712 CRASH REPORT Process <0.4314.0> with 0 neighbours crashed with reason: no function clause matching cowboy_req:do_reply(200, #{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>}, <<>>, <<"bar">>) line 712
2017-11-09 15:24:20.707 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.4313.0>,1,<0.4314.0>,function_clause,[{cowboy_req,do_reply,[200,#{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>},<<>>,<<"bar">>],[{file,"src/cowboy_req.erl"},{line,712}]},{http_handler,handle,3,[{file,"/home/pampa/pampa_pro/src/http_handler.erl"},{line,42}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,...},...]]},...}}
2017-11-09 15:24:41.818 [error] <0.619.0> /home/pampa/pampa_pro/src/http_handler.erl:24: Error: function handle/3 undefined
/home/pampa/pampa_pro/src/http_handler.erl:39: Error: syntax error before: '}'
2017-11-09 15:24:43.422 [error] <0.4372.0>@cowboy_req:do_reply:712 CRASH REPORT Process <0.4372.0> with 0 neighbours crashed with reason: no function clause matching cowboy_req:do_reply(200, #{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>}, <<>>, <<"bar">>) line 712
2017-11-09 15:24:43.423 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.4371.0>,1,<0.4372.0>,function_clause,[{cowboy_req,do_reply,[200,#{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>},<<>>,<<"bar">>],[{file,"src/cowboy_req.erl"},{line,712}]},{http_handler,handle,3,[{file,"/home/pampa/pampa_pro/src/http_handler.erl"},{line,42}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,...},...]]},...}}
2017-11-09 15:24:45.381 [error] <0.4379.0>@cowboy_req:do_reply:712 CRASH REPORT Process <0.4379.0> with 0 neighbours crashed with reason: no function clause matching cowboy_req:do_reply(200, #{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>}, <<>>, <<"bar">>) line 712
2017-11-09 15:24:45.383 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.4378.0>,1,<0.4379.0>,function_clause,[{cowboy_req,do_reply,[200,#{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>},<<>>,<<"bar">>],[{file,"src/cowboy_req.erl"},{line,712}]},{http_handler,handle,3,[{file,"/home/pampa/pampa_pro/src/http_handler.erl"},{line,42}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,...},...]]},...}}
2017-11-09 15:24:46.206 [error] <0.4385.0>@cowboy_req:do_reply:712 CRASH REPORT Process <0.4385.0> with 0 neighbours crashed with reason: no function clause matching cowboy_req:do_reply(200, #{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>}, <<>>, <<"bar">>) line 712
2017-11-09 15:24:46.207 [error] <0.648.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[my_http_listener,<0.4384.0>,1,<0.4385.0>,function_clause,[{cowboy_req,do_reply,[200,#{<<"content-length">> => <<"0">>,<<"content-type">> => <<"text/plain">>},<<>>,<<"bar">>],[{file,"src/cowboy_req.erl"},{line,712}]},{http_handler,handle,3,[{file,"/home/pampa/pampa_pro/src/http_handler.erl"},{line,42}]},{cowboy_handler,execute,2,[{file,"src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,205}]},{cowboy_stream_h,request_process,...},...]]},...}}
2017-11-09 15:26:24.903 [error] <0.619.0> /home/pampa/pampa_pro/src/http_handler.erl:52: Error: function handle/3 already defined
2017-11-09 15:28:20.140 [error] <0.619.0> /home/pampa/pampa_pro/src/tcp_handler.erl:1: Error: no module definition
2017-11-09 16:15:50.354 [error] <0.620.0> /home/pampa/pampa_pro/src/tcp_handler.erl:17: Error: function loop/2 undefined
/home/pampa/pampa_pro/src/tcp_handler.erl:20: Error: undefined macro 'TCP_TIMEOUT_MS'
2017-11-09 20:12:26.199 [error] <0.620.0> /home/pampa/pampa_pro/src/tcp_handler.erl:1: Error: no module definition
2017-11-09 20:22:24.258 [error] <0.620.0> /home/pampa/pampa_pro/src/tcp_handler.erl:31: Error: function init/1 already defined
2017-11-09 20:23:34.111 [error] <0.620.0> /home/pampa/pampa_pro/src/tcp_handler.erl:1: Error: no module definition
2017-11-09 20:36:42.650 [error] <0.620.0> /home/pampa/pampa_pro/src/tcp_handler.erl:41: Error: variable 'MsgerPid' is unbound
/home/pampa/pampa_pro/src/tcp_handler.erl:48: Warning: variable 'MsgerPid' is unused
2017-11-09 20:44:32.099 [error] <0.3658.0>@tcp_handler:init:32 CRASH REPORT Process <0.3658.0> with 0 neighbours crashed with reason: bad argument in call to io:format(<0.657.0>, "tcp init pid : ~p ~n", <0.3658.0>) in tcp_handler:init/1 line 32
2017-11-09 20:44:32.100 [error] <0.3658.0>@tcp_handler:init:32 Ranch listener my_tcp_listener terminated with reason: bad argument in call to io:format(<0.657.0>, "tcp init pid : ~p ~n", <0.3658.0>) in tcp_handler:init/1 line 32
2017-11-09 21:13:49.183 [error] <0.620.0> /home/pampa/pampa_pro/src/tcp_handler.erl:16: Error: function terminate/2 undefined
/home/pampa/pampa_pro/src/tcp_handler.erl:91: Error: syntax error before: ok
2017-11-09 21:17:00.132 [error] <0.6500.0> gen_server <0.6500.0> terminated with reason: <0.6501.0> in tcp_handler:terminate/2 line 90
2017-11-09 21:17:00.133 [error] <0.6500.0> CRASH REPORT Process <0.6500.0> with 0 neighbours exited with reason: <0.6501.0> in tcp_handler:terminate/2 line 90
2017-11-09 21:17:00.133 [error] <0.6500.0> Ranch listener my_tcp_listener terminated with reason: <0.6501.0>
2017-11-09 21:22:52.099 [error] <0.620.0> /home/pampa/pampa_pro/src/tcp_handler.erl:16: Error: function terminate/2 undefined
/home/pampa/pampa_pro/src/tcp_handler.erl:91: Error: syntax error before: ok
2017-11-09 21:23:37.359 [error] <0.7573.0>@rabbit_binary_generator:build_content_frames:95 Supervisor {<0.7573.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.4537>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.7575.0>, {<<"client 127.0.0.1:38400 -> 127.0.0.1:5672">>,1}) at <0.7576.0> exit with reason bad argument in call to erlang:size(none) in rabbit_binary_generator:build_content_frames/7 line 95 in context child_terminated
2017-11-09 21:23:37.360 [error] <0.7573.0> Supervisor {<0.7573.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.4537>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.7575.0>, {<<"client 127.0.0.1:38400 -> 127.0.0.1:5672">>,1}) at <0.7576.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 21:23:37.360 [error] emulator Error in process <0.7576.0> on node pampa_pro@localhost with exit value:
{badarg,[{erlang,size,[none],[]},{rabbit_binary_generator,build_content_frames,7,[{file,"src/rabbit_binary_generator.erl"},{line,95}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"src/rabbit_binary_generator.erl"},{line,70}]},{rabbit_writer,assemble_frames,5,[{file,"src/rabbit_writer.erl"},{line,311}]},{rabbit_writer,internal_send_command_async,3,[{file,"src/rabbit_writer.erl"},{line,341}]},{rabbit_writer,handle_message,3,[{file,"src/rabbit_writer.erl"},{line,209}]},{rabbit_writer,mainloop1,2,[{file,"src/rabbit_writer.erl"},{line,193}]},{rabbit_writer,mainloop,2,[{file,"src/rabbit_writer.erl"},{line,184}]}]}
2017-11-09 21:25:41.731 [error] <0.4168.0> gen_server <0.4168.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2017-11-09 21:25:41.732 [error] <0.4168.0> CRASH REPORT Process <0.4168.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1170
2017-11-09 21:25:41.732 [error] <0.4167.0> Supervisor {<0.4167.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:51849 -> 127.0.0.1:5672">>,1}) at <0.4168.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2017-11-09 21:25:41.733 [error] <0.4167.0> Supervisor {<0.4167.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:51849 -> 127.0.0.1:5672">>,1}) at <0.4168.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 21:25:41.733 [error] <0.4169.0> gen_server <0.4169.0> terminated with reason: shutdown in gen:do_call/4 line 177
2017-11-09 21:25:41.733 [error] <0.4167.0> Supervisor {<0.4167.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.4160.0>, 1, <0.4168.0>, {<<"client 127.0.0.1:51849 -> 127.0.0.1:5672">>,1}) at <0.4169.0> exit with reason shutdown in context shutdown_error
2017-11-09 21:25:41.733 [error] <0.6512.0> gen_server <0.6512.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2017-11-09 21:25:41.734 [error] <0.6512.0> CRASH REPORT Process <0.6512.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1170
2017-11-09 21:25:41.734 [error] <0.4954.0> gen_server <0.4954.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2017-11-09 21:25:41.734 [error] <0.934.0> gen_server <0.934.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2017-11-09 21:25:41.734 [error] <0.4954.0> CRASH REPORT Process <0.4954.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1170
2017-11-09 21:25:41.734 [error] <0.934.0> CRASH REPORT Process <0.934.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1170
2017-11-09 21:25:41.735 [error] <0.4645.0> gen_server <0.4645.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2017-11-09 21:25:41.735 [error] <0.4645.0> CRASH REPORT Process <0.4645.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1170
2017-11-09 21:25:41.735 [error] <0.5362.0> gen_server <0.5362.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2017-11-09 21:25:41.736 [error] <0.5362.0> CRASH REPORT Process <0.5362.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1170
2017-11-09 21:25:41.736 [error] <0.6511.0> Supervisor {<0.6511.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:54018 -> 127.0.0.1:5672">>,1}) at <0.6512.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2017-11-09 21:25:41.737 [error] <0.6511.0> Supervisor {<0.6511.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:54018 -> 127.0.0.1:5672">>,1}) at <0.6512.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 21:25:41.737 [error] <0.4953.0> Supervisor {<0.4953.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:52547 -> 127.0.0.1:5672">>,1}) at <0.4954.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2017-11-09 21:25:41.737 [error] <0.933.0> Supervisor {<0.933.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:50704 -> 127.0.0.1:5672">>,1}) at <0.934.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2017-11-09 21:25:41.738 [error] <0.933.0> Supervisor {<0.933.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:50704 -> 127.0.0.1:5672">>,1}) at <0.934.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 21:25:41.738 [error] <0.4953.0> Supervisor {<0.4953.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:52547 -> 127.0.0.1:5672">>,1}) at <0.4954.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 21:25:41.738 [error] <0.4644.0> Supervisor {<0.4644.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:44965 -> 127.0.0.1:5672">>,1}) at <0.4645.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2017-11-09 21:25:41.739 [error] <0.4644.0> Supervisor {<0.4644.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:44965 -> 127.0.0.1:5672">>,1}) at <0.4645.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 21:25:41.739 [error] <0.4329.0> gen_server <0.4329.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2017-11-09 21:25:41.739 [error] <0.4329.0> CRASH REPORT Process <0.4329.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1170
2017-11-09 21:25:41.740 [error] <0.5361.0> Supervisor {<0.5361.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:52781 -> 127.0.0.1:5672">>,1}) at <0.5362.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2017-11-09 21:25:41.740 [error] <0.5361.0> Supervisor {<0.5361.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:52781 -> 127.0.0.1:5672">>,1}) at <0.5362.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 21:25:41.740 [error] <0.935.0> gen_server <0.935.0> terminated with reason: shutdown in gen:do_call/4 line 177
2017-11-09 21:25:41.740 [error] <0.5739.0> gen_server <0.5739.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2017-11-09 21:25:41.740 [error] <0.4646.0> gen_server <0.4646.0> terminated with reason: shutdown in gen:do_call/4 line 177
2017-11-09 21:25:41.741 [error] <0.5739.0> CRASH REPORT Process <0.5739.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1170
2017-11-09 21:25:41.741 [error] <0.6732.0> gen_server <0.6732.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2017-11-09 21:25:41.741 [error] <0.6732.0> CRASH REPORT Process <0.6732.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1170
2017-11-09 21:25:41.742 [error] <0.933.0> Supervisor {<0.933.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.924.0>, 1, <0.934.0>, {<<"client 127.0.0.1:50704 -> 127.0.0.1:5672">>,1}) at <0.935.0> exit with reason shutdown in context shutdown_error
2017-11-09 21:25:41.742 [error] <0.4644.0> Supervisor {<0.4644.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.4637.0>, 1, <0.4645.0>, {<<"client 127.0.0.1:44965 -> 127.0.0.1:5672">>,1}) at <0.4646.0> exit with reason shutdown in context shutdown_error
2017-11-09 21:25:41.743 [error] <0.4328.0> Supervisor {<0.4328.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:36250 -> 127.0.0.1:5672">>,1}) at <0.4329.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2017-11-09 21:25:41.743 [error] <0.4328.0> Supervisor {<0.4328.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:36250 -> 127.0.0.1:5672">>,1}) at <0.4329.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 21:25:41.743 [error] <0.5738.0> Supervisor {<0.5738.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:41802 -> 127.0.0.1:5672">>,1}) at <0.5739.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2017-11-09 21:25:41.744 [error] <0.5738.0> Supervisor {<0.5738.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:41802 -> 127.0.0.1:5672">>,1}) at <0.5739.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 21:25:41.744 [error] <0.6731.0> Supervisor {<0.6731.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:42589 -> 127.0.0.1:5672">>,1}) at <0.6732.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2017-11-09 21:25:41.745 [error] <0.6731.0> Supervisor {<0.6731.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:42589 -> 127.0.0.1:5672">>,1}) at <0.6732.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 21:25:41.745 [error] <0.6513.0> gen_server <0.6513.0> terminated with reason: shutdown in gen:do_call/4 line 177
2017-11-09 21:25:41.745 [error] <0.5363.0> gen_server <0.5363.0> terminated with reason: shutdown in gen:do_call/4 line 177
2017-11-09 21:25:41.745 [error] <0.5361.0> Supervisor {<0.5361.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.5354.0>, 1, <0.5362.0>, {<<"client 127.0.0.1:52781 -> 127.0.0.1:5672">>,1}) at <0.5363.0> exit with reason shutdown in context shutdown_error
2017-11-09 21:25:41.745 [error] <0.6511.0> Supervisor {<0.6511.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.6504.0>, 1, <0.6512.0>, {<<"client 127.0.0.1:54018 -> 127.0.0.1:5672">>,1}) at <0.6513.0> exit with reason shutdown in context shutdown_error
2017-11-09 21:25:41.746 [error] <0.6733.0> gen_server <0.6733.0> terminated with reason: shutdown in gen:do_call/4 line 177
2017-11-09 21:25:41.746 [error] <0.6731.0> Supervisor {<0.6731.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.6724.0>, 1, <0.6732.0>, {<<"client 127.0.0.1:42589 -> 127.0.0.1:5672">>,1}) at <0.6733.0> exit with reason shutdown in context shutdown_error
2017-11-09 21:25:44.705 [error] <0.7833.0>@rabbit_binary_generator:build_content_frames:95 Supervisor {<0.7833.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.4539>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.7835.0>, {<<"client 127.0.0.1:35888 -> 127.0.0.1:5672">>,1}) at <0.7836.0> exit with reason bad argument in call to erlang:size(none) in rabbit_binary_generator:build_content_frames/7 line 95 in context child_terminated
2017-11-09 21:25:44.705 [error] <0.7833.0> Supervisor {<0.7833.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.4539>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.7835.0>, {<<"client 127.0.0.1:35888 -> 127.0.0.1:5672">>,1}) at <0.7836.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 21:25:44.705 [error] emulator Error in process <0.7836.0> on node pampa_pro@localhost with exit value:
{badarg,[{erlang,size,[none],[]},{rabbit_binary_generator,build_content_frames,7,[{file,"src/rabbit_binary_generator.erl"},{line,95}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"src/rabbit_binary_generator.erl"},{line,70}]},{rabbit_writer,assemble_frames,5,[{file,"src/rabbit_writer.erl"},{line,311}]},{rabbit_writer,internal_send_command_async,3,[{file,"src/rabbit_writer.erl"},{line,341}]},{rabbit_writer,handle_message,3,[{file,"src/rabbit_writer.erl"},{line,209}]},{rabbit_writer,mainloop1,2,[{file,"src/rabbit_writer.erl"},{line,193}]},{rabbit_writer,mainloop,2,[{file,"src/rabbit_writer.erl"},{line,184}]}]}
2017-11-09 21:27:39.925 [error] <0.8165.0>@rabbit_binary_generator:build_content_frames:95 Supervisor {<0.8165.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.4590>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.8167.0>, {<<"client 127.0.0.1:35496 -> 127.0.0.1:5672">>,1}) at <0.8168.0> exit with reason bad argument in call to erlang:size(<0.8155.0>) in rabbit_binary_generator:build_content_frames/7 line 95 in context child_terminated
2017-11-09 21:27:39.926 [error] <0.8165.0> Supervisor {<0.8165.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.4590>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.8167.0>, {<<"client 127.0.0.1:35496 -> 127.0.0.1:5672">>,1}) at <0.8168.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 21:27:39.926 [error] emulator Error in process <0.8168.0> on node pampa_pro@localhost with exit value:
{badarg,[{erlang,size,[<0.8155.0>],[]},{rabbit_binary_generator,build_content_frames,7,[{file,"src/rabbit_binary_generator.erl"},{line,95}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"src/rabbit_binary_generator.erl"},{line,70}]},{rabbit_writer,assemble_frames,5,[{file,"src/rabbit_writer.erl"},{line,311}]},{rabbit_writer,internal_send_command_async,3,[{file,"src/rabbit_writer.erl"},{line,341}]},{rabbit_writer,handle_message,3,[{file,"src/rabbit_writer.erl"},{line,209}]},{rabbit_writer,mainloop1,2,[{file,"src/rabbit_writer.erl"},{line,193}]},{rabbit_writer,mainloop,2,[{file,"src/rabbit_writer.erl"},{line,184}]}]}
2017-11-09 21:32:20.793 [error] <0.8693.0> gen_server <0.8693.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2017-11-09 21:32:20.794 [error] <0.8693.0> CRASH REPORT Process <0.8693.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1170
2017-11-09 21:32:20.794 [error] <0.8692.0> Supervisor {<0.8692.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:57326 -> 127.0.0.1:5672">>,1}) at <0.8693.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2017-11-09 21:32:20.848 [error] <0.8692.0> Supervisor {<0.8692.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:57326 -> 127.0.0.1:5672">>,1}) at <0.8693.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 21:32:20.848 [error] <0.8694.0> gen_server <0.8694.0> terminated with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.8693.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-VOgPr_UWkQtrH0QZVsiv0A">>,1,false,<<"hello1">>,<<>>},{amqp_msg,{'P_basic',undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"fe\r\n">>}},60000]}} in gen_server2:call/3 line 327
2017-11-09 21:32:20.849 [error] <0.8694.0> CRASH REPORT Process <0.8694.0> with 0 neighbours exited with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.8693.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-VOgPr_UWkQtrH0QZVsiv0A">>,1,false,<<"hello1">>,<<>>},{amqp_msg,{'P_basic',undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"fe\r\n">>}},60000]}} in gen_server2:call/3 line 327
2017-11-09 21:32:20.850 [error] <0.8692.0> Supervisor {<0.8692.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.8685.0>, 1, <0.8693.0>, {<<"client 127.0.0.1:57326 -> 127.0.0.1:5672">>,1}) at <0.8694.0> exit with reason {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.8693.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-VOgPr_UWkQtrH0QZVsiv0A">>,1,false,<<"hello1">>,<<>>},{amqp_msg,{'P_basic',undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"fe\r\n">>}},60000]}} in context shutdown_error
2017-11-09 21:32:20.850 [error] <0.8685.0> gen_server <0.8685.0> terminated with reason: {channel0_died,method_field_shortstr_overflow}
2017-11-09 21:32:20.851 [error] <0.8685.0> CRASH REPORT Process <0.8685.0> with 0 neighbours exited with reason: {channel0_died,method_field_shortstr_overflow} in gen_server:handle_common_reply/8 line 726
2017-11-09 21:32:20.851 [error] <0.8683.0> Supervisor {<0.8683.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.8684.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[#Fun<amqp_..>,...],...}) at <0.8685.0> exit with reason {channel0_died,method_field_shortstr_overflow} in context child_terminated
2017-11-09 21:32:20.852 [error] <0.8683.0> Supervisor {<0.8683.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.8684.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,60000,none,[#Fun<amqp_..>,...],...}) at <0.8685.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 21:55:06.850 [error] <0.1136.0>@rabbit_binary_generator:build_content_frames:95 Supervisor {<0.1136.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.1621>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.1138.0>, {<<"client 127.0.0.1:46462 -> 127.0.0.1:5672">>,1}) at <0.1139.0> exit with reason bad argument in call to erlang:size(<0.1124.0>) in rabbit_binary_generator:build_content_frames/7 line 95 in context child_terminated
2017-11-09 21:55:06.851 [error] <0.1136.0> Supervisor {<0.1136.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.1621>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.1138.0>, {<<"client 127.0.0.1:46462 -> 127.0.0.1:5672">>,1}) at <0.1139.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 21:55:06.851 [error] emulator Error in process <0.1139.0> on node pampa_pro@localhost with exit value:
{badarg,[{erlang,size,[<0.1124.0>],[]},{rabbit_binary_generator,build_content_frames,7,[{file,"src/rabbit_binary_generator.erl"},{line,95}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"src/rabbit_binary_generator.erl"},{line,70}]},{rabbit_writer,assemble_frames,5,[{file,"src/rabbit_writer.erl"},{line,311}]},{rabbit_writer,internal_send_command_async,3,[{file,"src/rabbit_writer.erl"},{line,341}]},{rabbit_writer,handle_message,3,[{file,"src/rabbit_writer.erl"},{line,209}]},{rabbit_writer,mainloop1,2,[{file,"src/rabbit_writer.erl"},{line,193}]},{rabbit_writer,mainloop,2,[{file,"src/rabbit_writer.erl"},{line,184}]}]}
2017-11-09 22:03:27.249 [error] emulator Error in process <0.972.0> on node pampa_pro@localhost with exit value:
{badarg,[{erlang,size,[<0.956.0>],[]},{rabbit_binary_generator,build_content_frames,7,[{file,"src/rabbit_binary_generator.erl"},{line,95}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"src/rabbit_binary_generator.erl"},{line,70}]},{rabbit_writer,assemble_frames,5,[{file,"src/rabbit_writer.erl"},{line,311}]},{rabbit_writer,internal_send_command_async,3,[{file,"src/rabbit_writer.erl"},{line,341}]},{rabbit_writer,handle_message,3,[{file,"src/rabbit_writer.erl"},{line,209}]},{rabbit_writer,mainloop1,2,[{file,"src/rabbit_writer.erl"},{line,193}]},{rabbit_writer,mainloop,2,[{file,"src/rabbit_writer.erl"},{line,184}]}]}
2017-11-09 22:03:27.250 [error] <0.969.0>@rabbit_binary_generator:build_content_frames:95 Supervisor {<0.969.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.1454>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.971.0>, {<<"client 127.0.0.1:43942 -> 127.0.0.1:5672">>,1}) at <0.972.0> exit with reason bad argument in call to erlang:size(<0.956.0>) in rabbit_binary_generator:build_content_frames/7 line 95 in context child_terminated
2017-11-09 22:03:27.251 [error] <0.969.0> Supervisor {<0.969.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.1454>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.971.0>, {<<"client 127.0.0.1:43942 -> 127.0.0.1:5672">>,1}) at <0.972.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 22:08:59.292 [error] <0.1001.0>@rabbit_binary_generator:build_content_frames:95 Supervisor {<0.1001.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.1487>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.1004.0>, {<<"client 127.0.0.1:58181 -> 127.0.0.1:5672">>,1}) at <0.1005.0> exit with reason bad argument in call to erlang:size(<0.989.0>) in rabbit_binary_generator:build_content_frames/7 line 95 in context child_terminated
2017-11-09 22:08:59.292 [error] <0.1001.0> Supervisor {<0.1001.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.1487>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.1004.0>, {<<"client 127.0.0.1:58181 -> 127.0.0.1:5672">>,1}) at <0.1005.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 22:08:59.292 [error] emulator Error in process <0.1005.0> on node pampa_pro@localhost with exit value:
{badarg,[{erlang,size,[<0.989.0>],[]},{rabbit_binary_generator,build_content_frames,7,[{file,"src/rabbit_binary_generator.erl"},{line,95}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"src/rabbit_binary_generator.erl"},{line,70}]},{rabbit_writer,assemble_frames,5,[{file,"src/rabbit_writer.erl"},{line,311}]},{rabbit_writer,internal_send_command_async,3,[{file,"src/rabbit_writer.erl"},{line,341}]},{rabbit_writer,handle_message,3,[{file,"src/rabbit_writer.erl"},{line,209}]},{rabbit_writer,mainloop1,2,[{file,"src/rabbit_writer.erl"},{line,193}]},{rabbit_writer,mainloop,2,[{file,"src/rabbit_writer.erl"},{line,184}]}]}
2017-11-09 22:09:52.447 [error] <0.3387.0> gen_server <0.3387.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2017-11-09 22:09:52.447 [error] <0.3387.0> CRASH REPORT Process <0.3387.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1170
2017-11-09 22:09:52.447 [error] <0.3386.0> Supervisor {<0.3386.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:45458 -> 127.0.0.1:5672">>,1}) at <0.3387.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2017-11-09 22:09:52.448 [error] <0.3386.0> Supervisor {<0.3386.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:45458 -> 127.0.0.1:5672">>,1}) at <0.3387.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 22:09:52.448 [error] <0.3388.0> gen_server <0.3388.0> terminated with reason: shutdown in gen:do_call/4 line 177
2017-11-09 22:10:41.600 [error] <0.3449.0> gen_server <0.3449.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2017-11-09 22:10:41.600 [error] <0.3449.0> CRASH REPORT Process <0.3449.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1170
2017-11-09 22:10:41.601 [error] <0.3448.0> Supervisor {<0.3448.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:39171 -> 127.0.0.1:5672">>,1}) at <0.3449.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2017-11-09 22:10:41.601 [error] <0.3448.0> Supervisor {<0.3448.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:39171 -> 127.0.0.1:5672">>,1}) at <0.3449.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 22:10:41.601 [error] <0.3450.0> gen_server <0.3450.0> terminated with reason: shutdown in gen:do_call/4 line 177
2017-11-09 22:10:41.601 [error] <0.3448.0> Supervisor {<0.3448.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.3441.0>, 1, <0.3449.0>, {<<"client 127.0.0.1:39171 -> 127.0.0.1:5672">>,1}) at <0.3450.0> exit with reason shutdown in context shutdown_error
2017-11-09 22:13:08.322 [error] <0.620.0> /home/pampa/pampa_pro/src/msger.erl:71: Error: variable 'DeadUserId' is unbound
2017-11-09 22:13:26.510 [error] <0.3591.0>@rabbit_binary_generator:build_content_frames:95 CRASH REPORT Process <0.3591.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(<0.3578.0>) in rabbit_binary_generator:build_content_frames/7 line 95
2017-11-09 22:13:26.511 [error] <0.3588.0>@rabbit_binary_generator:build_content_frames:95 Supervisor {<0.3588.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.3876>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.3590.0>, {<<"client 127.0.0.1:42189 -> 127.0.0.1:5672">>,1}) at <0.3591.0> exit with reason bad argument in call to erlang:size(<0.3578.0>) in rabbit_binary_generator:build_content_frames/7 line 95 in context child_terminated
2017-11-09 22:13:26.512 [error] <0.3588.0> Supervisor {<0.3588.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.3876>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.3590.0>, {<<"client 127.0.0.1:42189 -> 127.0.0.1:5672">>,1}) at <0.3591.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 22:21:08.777 [error] <0.975.0>@rabbit_binary_generator:build_content_frames:95 CRASH REPORT Process <0.975.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(<0.960.0>) in rabbit_binary_generator:build_content_frames/7 line 95
2017-11-09 22:21:08.777 [error] <0.972.0>@rabbit_binary_generator:build_content_frames:95 Supervisor {<0.972.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.1457>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.974.0>, {<<"client 127.0.0.1:55979 -> 127.0.0.1:5672">>,1}) at <0.975.0> exit with reason bad argument in call to erlang:size(<0.960.0>) in rabbit_binary_generator:build_content_frames/7 line 95 in context child_terminated
2017-11-09 22:21:08.778 [error] <0.972.0> Supervisor {<0.972.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.1457>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.974.0>, {<<"client 127.0.0.1:55979 -> 127.0.0.1:5672">>,1}) at <0.975.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 22:39:32.426 [error] <0.1152.0>@lists:reverse:147 Supervisor {<0.1152.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.1637>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.1154.0>, {<<"client 127.0.0.1:42317 -> 127.0.0.1:5672">>,1}) at <0.1155.0> exit with reason no function clause matching lists:reverse({'USER_DEAD',<0.1140.0>}) line 147 in context child_terminated
2017-11-09 22:39:32.426 [error] <0.1152.0> Supervisor {<0.1152.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.1637>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.1154.0>, {<<"client 127.0.0.1:42317 -> 127.0.0.1:5672">>,1}) at <0.1155.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 22:39:32.427 [error] emulator Error in process <0.1155.0> on node pampa_pro@localhost with exit value:
{function_clause,[{lists,reverse,[{'USER_DEAD',<0.1140.0>}],[{file,"lists.erl"},{line,147}]},{rabbit_binary_generator,build_content_frames,3,[{file,"src/rabbit_binary_generator.erl"},{line,81}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"src/rabbit_binary_generator.erl"},{line,70}]},{rabbit_writer,assemble_frames,5,[{file,"src/rabbit_writer.erl"},{line,311}]},{rabbit_writer,internal_send_command_async,3,[{file,"src/rabbit_writer.erl"},{line,341}]},{rabbit_writer,handle_message,3,[{file,"src/rabbit_writer.erl"},{line,209}]},{rabbit_writer,mainloop1,2,[{file,"src/rabbit_writer.erl"},{line,193}]},{rabbit_writer,mainloop,2,[{file,"src/rabbit_writer.erl"},{line,184}]}]}
2017-11-09 22:40:42.319 [error] emulator Error in process <0.3463.0> on node pampa_pro@localhost with exit value:
{badarg,[{msger,loop,1,[{file,"/home/pampa/pampa_pro/src/msger.erl"},{line,86}]}]}
2017-11-09 22:41:39.827 [error] <0.3474.0> gen_server <0.3474.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2017-11-09 22:41:39.827 [error] <0.3474.0> CRASH REPORT Process <0.3474.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1170
2017-11-09 22:41:39.828 [error] <0.3473.0> Supervisor {<0.3473.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:45691 -> 127.0.0.1:5672">>,1}) at <0.3474.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2017-11-09 22:41:39.828 [error] <0.3473.0> Supervisor {<0.3473.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:45691 -> 127.0.0.1:5672">>,1}) at <0.3474.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 22:41:39.828 [error] <0.3475.0> gen_server <0.3475.0> terminated with reason: shutdown in gen:do_call/4 line 177
2017-11-09 22:41:39.828 [error] <0.3473.0> Supervisor {<0.3473.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.3466.0>, 1, <0.3474.0>, {<<"client 127.0.0.1:45691 -> 127.0.0.1:5672">>,1}) at <0.3475.0> exit with reason shutdown in context shutdown_error
2017-11-09 22:41:56.121 [error] emulator Error in process <0.3659.0> on node pampa_pro@localhost with exit value:
{badarg,[{msger,loop,1,[{file,"/home/pampa/pampa_pro/src/msger.erl"},{line,86}]}]}
2017-11-09 22:43:02.110 [error] emulator Error in process <0.1015.0> on node pampa_pro@localhost with exit value:
{badarg,[{erlang,size,[<0.1000.0>],[]},{rabbit_binary_generator,build_content_frames,7,[{file,"src/rabbit_binary_generator.erl"},{line,95}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"src/rabbit_binary_generator.erl"},{line,70}]},{rabbit_writer,assemble_frames,5,[{file,"src/rabbit_writer.erl"},{line,311}]},{rabbit_writer,internal_send_command_async,3,[{file,"src/rabbit_writer.erl"},{line,341}]},{rabbit_writer,handle_message,3,[{file,"src/rabbit_writer.erl"},{line,209}]},{rabbit_writer,mainloop1,2,[{file,"src/rabbit_writer.erl"},{line,193}]},{rabbit_writer,mainloop,2,[{file,"src/rabbit_writer.erl"},{line,184}]}]}
2017-11-09 22:43:02.111 [error] <0.1012.0>@rabbit_binary_generator:build_content_frames:95 Supervisor {<0.1012.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.1497>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.1014.0>, {<<"client 127.0.0.1:57291 -> 127.0.0.1:5672">>,1}) at <0.1015.0> exit with reason bad argument in call to erlang:size(<0.1000.0>) in rabbit_binary_generator:build_content_frames/7 line 95 in context child_terminated
2017-11-09 22:43:02.111 [error] <0.1012.0> Supervisor {<0.1012.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.1497>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.1014.0>, {<<"client 127.0.0.1:57291 -> 127.0.0.1:5672">>,1}) at <0.1015.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 22:43:49.296 [error] <0.3410.0>@rabbit_binary_generator:build_content_frames:95 CRASH REPORT Process <0.3410.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(<0.3397.0>) in rabbit_binary_generator:build_content_frames/7 line 95
2017-11-09 22:43:49.297 [error] <0.3407.0>@rabbit_binary_generator:build_content_frames:95 Supervisor {<0.3407.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.3839>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.3409.0>, {<<"client 127.0.0.1:36114 -> 127.0.0.1:5672">>,1}) at <0.3410.0> exit with reason bad argument in call to erlang:size(<0.3397.0>) in rabbit_binary_generator:build_content_frames/7 line 95 in context child_terminated
2017-11-09 22:43:49.297 [error] <0.3407.0> Supervisor {<0.3407.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.3839>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.3409.0>, {<<"client 127.0.0.1:36114 -> 127.0.0.1:5672">>,1}) at <0.3410.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 22:44:16.624 [error] <0.1293.0>@rabbit_binary_generator:build_content_frames:95 CRASH REPORT Process <0.1293.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(<0.1278.0>) in rabbit_binary_generator:build_content_frames/7 line 95
2017-11-09 22:44:16.625 [error] <0.1290.0>@rabbit_binary_generator:build_content_frames:95 Supervisor {<0.1290.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.1775>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.1292.0>, {<<"client 127.0.0.1:34271 -> 127.0.0.1:5672">>,1}) at <0.1293.0> exit with reason bad argument in call to erlang:size(<0.1278.0>) in rabbit_binary_generator:build_content_frames/7 line 95 in context child_terminated
2017-11-09 22:44:16.626 [error] <0.1290.0> Supervisor {<0.1290.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.1775>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.1292.0>, {<<"client 127.0.0.1:34271 -> 127.0.0.1:5672">>,1}) at <0.1293.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 22:44:54.734 [error] <0.3380.0>@rabbit_binary_generator:build_content_frames:95 CRASH REPORT Process <0.3380.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(<0.3367.0>) in rabbit_binary_generator:build_content_frames/7 line 95
2017-11-09 22:44:54.735 [error] <0.3377.0>@rabbit_binary_generator:build_content_frames:95 Supervisor {<0.3377.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.3839>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.3379.0>, {<<"client 127.0.0.1:34265 -> 127.0.0.1:5672">>,1}) at <0.3380.0> exit with reason bad argument in call to erlang:size(<0.3367.0>) in rabbit_binary_generator:build_content_frames/7 line 95 in context child_terminated
2017-11-09 22:44:54.735 [error] <0.3377.0> Supervisor {<0.3377.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.3839>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.3379.0>, {<<"client 127.0.0.1:34265 -> 127.0.0.1:5672">>,1}) at <0.3380.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 22:53:45.185 [error] <0.968.0>@rabbit_binary_generator:build_content_frames:95 Supervisor {<0.968.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.1454>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.970.0>, {<<"client 127.0.0.1:45318 -> 127.0.0.1:5672">>,1}) at <0.971.0> exit with reason bad argument in call to erlang:size(<0.956.0>) in rabbit_binary_generator:build_content_frames/7 line 95 in context child_terminated
2017-11-09 22:53:45.186 [error] <0.968.0> Supervisor {<0.968.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.1454>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.970.0>, {<<"client 127.0.0.1:45318 -> 127.0.0.1:5672">>,1}) at <0.971.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 22:53:45.186 [error] emulator Error in process <0.971.0> on node pampa_pro@localhost with exit value:
{badarg,[{erlang,size,[<0.956.0>],[]},{rabbit_binary_generator,build_content_frames,7,[{file,"src/rabbit_binary_generator.erl"},{line,95}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"src/rabbit_binary_generator.erl"},{line,70}]},{rabbit_writer,assemble_frames,5,[{file,"src/rabbit_writer.erl"},{line,311}]},{rabbit_writer,internal_send_command_async,3,[{file,"src/rabbit_writer.erl"},{line,341}]},{rabbit_writer,handle_message,3,[{file,"src/rabbit_writer.erl"},{line,209}]},{rabbit_writer,mainloop1,2,[{file,"src/rabbit_writer.erl"},{line,193}]},{rabbit_writer,mainloop,2,[{file,"src/rabbit_writer.erl"},{line,184}]}]}
2017-11-09 22:58:21.489 [error] <0.3558.0>@lists:reverse:147 Supervisor {<0.3558.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.3839>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.3560.0>, {<<"client 127.0.0.1:60079 -> 127.0.0.1:5672">>,1}) at <0.3561.0> exit with reason no function clause matching lists:reverse(<0.3548.0>) line 147 in context child_terminated
2017-11-09 22:58:21.490 [error] <0.3558.0> Supervisor {<0.3558.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.3839>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.3560.0>, {<<"client 127.0.0.1:60079 -> 127.0.0.1:5672">>,1}) at <0.3561.0> exit with reason reached_max_restart_intensity in context shutdown
2017-11-09 22:58:21.490 [error] emulator Error in process <0.3561.0> on node pampa_pro@localhost with exit value:
{function_clause,[{lists,reverse,[<0.3548.0>],[{file,"lists.erl"},{line,147}]},{rabbit_binary_generator,build_content_frames,3,[{file,"src/rabbit_binary_generator.erl"},{line,81}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"src/rabbit_binary_generator.erl"},{line,70}]},{rabbit_writer,assemble_frames,5,[{file,"src/rabbit_writer.erl"},{line,311}]},{rabbit_writer,internal_send_command_async,3,[{file,"src/rabbit_writer.erl"},{line,341}]},{rabbit_writer,handle_message,3,[{file,"src/rabbit_writer.erl"},{line,209}]},{rabbit_writer,mainloop1,2,[{file,"src/rabbit_writer.erl"},{line,193}]},{rabbit_writer,mainloop,2,[{file,"src/rabbit_writer.erl"},{line,184}]}]}
2017-11-09 23:01:47.673 [error] emulator Error in process <0.1070.0> on node pampa_pro@localhost with exit value:
{badarg,[{erlang,size,[<0.1053.0>],[]},{rabbit_binary_generator,build_content_frames,7,[{file,"src/rabbit_binary_generator.erl"},{line,95}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"src/rabbit_binary_generator.erl"},{line,70}]},{rabbit_writer,assemble_frames,5,[{file,"src/rabbit_writer.erl"},{line,311}]},{rabbit_writer,internal_send_command_async,3,[{file,"src/rabbit_writer.erl"},{line,341}]},{rabbit_writer,handle_message,3,[{file,"src/rabbit_writer.erl"},{line,209}]},{rabbit_writer,mainloop1,2,[{file,"src/rabbit_writer.erl"},{line,193}]},{rabbit_writer,mainloop,2,[{file,"src/rabbit_writer.erl"},{line,184}]}]}
2017-11-09 23:01:47.675 [error] <0.1067.0>@rabbit_binary_generator:build_content_frames:95 Supervisor {<0.1067.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.1551>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.1069.0>, {<<"client 127.0.0.1:47367 -> 127.0.0.1:5672">>,1}) at <0.1070.0> exit with reason bad argument in call to erlang:size(<0.1053.0>) in rabbit_binary_generator:build_content_frames/7 line 95 in context child_terminated
2017-11-09 23:01:47.675 [error] <0.1067.0> Supervisor {<0.1067.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.1551>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.1069.0>, {<<"client 127.0.0.1:47367 -> 127.0.0.1:5672">>,1}) at <0.1070.0> exit with reason reached_max_restart_intensity in context shutdown
